In [33]:
#USN:01FE15BCS237
#Roll:244
#lAB2_Assignment_1

import tensorflow as tf
x=tf.constant([1.1,2.2,3.3,4.4])
y=tf.constant([2.2,3.3,4.4,5.5])

mean_x=tf.reduce_mean(x)
mean_y=tf.reduce_mean(y)

ss=tf.Session()
print (ss.run(mean_x))
print (ss.run(mean_y))


x_x=tf.subtract(x,mean_x)


y_y=tf.subtract(y,mean_y)


sqr1=tf.square(x_x)

sqr2=tf.square(y_y)


var1=tf.reduce_sum(sqr1)

var2=tf.reduce_sum(sqr2)

print (ss.run(var1))

print (ss.run(var2))

tmp=tf.multiply(x_x,y_y)
cov=tf.reduce_sum(tmp)
print (ss.run(cov))


m=tf.div(cov,var1)
print (ss.run(m))

tmp2=tf.multiply(m,mean_x)
c=tf.subtract(mean_y,tmp2)
print (ss.run(c))


#Estimate y using y=mx+c
for c in range(1,10):
    for m in range(1,10):
        prdcted_y=tf.add(tf.multiply(x,m),c)
        print (ss.run(prdcted_y))
        #Finding RMS ERROR for different values of m and c
        rms = tf.div(tf.sqrt(tf.reduce_mean(tf.squared_difference(prdcted_y, y))),tf.to_float(tf.size(x)))
        print(ss.run(rms))
        
    



2.75
3.85
6.05
6.05
6.05
1.0
1.1
[ 2.0999999   3.20000005  4.30000019  5.4000001 ]
0.025
[ 3.20000005  5.4000001   7.5999999   9.80000019]
0.730368
[  4.30000019   7.60000038  10.89999962  14.20000076]
1.48345
[  5.4000001    9.80000019  14.19999981  18.60000038]
2.23656
[  6.5  12.   17.5  23. ]
2.98967
[  7.60000038  14.20000076  20.79999924  27.40000153]
3.74278
[  8.70000076  16.40000153  24.10000038  31.80000114]
4.4959
[  9.80000019  18.60000038  27.39999962  36.20000076]
5.24902
[ 10.90000057  20.80000114  30.69999886  40.60000229]
6.00214
[ 3.0999999   4.19999981  5.30000019  6.4000001 ]
0.225
[  4.19999981   6.4000001    8.60000038  10.80000019]
0.962906
[  5.30000019   8.60000038  11.89999962  15.20000076]
1.7141
[  6.4000001   10.80000019  15.19999981  19.60000038]
2.46646
[  7.5  13.   18.5  24. ]
3.21918
[  8.60000038  15.20000076  21.79999924  28.40000153]
3.97205
[  9.70000076  17.40000153  25.10000038  32.80000305]
4.725
[ 10.80000019  19.60000038  28.39999962  37.20000